version: 0.0.{build}

shallow_clone: true
skip_branch_with_pr: true

max_jobs: 1
configuration: Release

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: $version = (cat version.txt); Set-AppveyorBuildVariable 'nugetVersion' $version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(nugetVersion)
  package_version: $(nugetVersion)
  assembly_version: $(nugetVersion)
  file_version: $(nugetVersion)
  informational_version: $(nugetVersion)

before_build:
  - cd project
  - nuget restore

build:
  parallel: true
  project: project/Snapper.sln
  publish_nuget: true

test: off

test_script:
  - ps: dotnet test --no-build
  - ps: dotnet test Tests/Snapper.Nunit.Tests/Snapper.Nunit.Tests.csproj --logger:Appveyor --no-build

deploy:
  - provider: NuGet
    api_key:
      secure: oXT0QCxjs1xdzIwv4hbyr6EUCeen7PNVzrghmozBSKBNOOq4h8acf3xAEIlA1eEz
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

skip_commits:
  files:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - LICENSE
  - README.md
  - CHANGELOG.md
  - docs/
